
worldDesc = {

	northWestCorner      : "Overgrown area of trees and plants. The foliage is so thick that you can't see any further."
	northernRidgeWest    : "The area opens up to reveal a clearing. A flat rock ledge protrudes out over the sea."
	northernRidgeEast    : "The area opens up to reveal a clearing. A flat rock ledge protrudes out over the sea."
	northernWall         : "Overgrown area of trees and plants. The foliage is so thick that you can't see any further."
	northernPoint        : "You feel like you've reached the edge of the island. There are a few more rocks protruding from teh sea, but they lead to nowhere."
	northWestView        : "Although the climb down to the beach below would be manageable for a professional climber, it is too steep for you."
	northWestBunker      : "There is a small concrete structure with a thick metal door and no windows."
	northClearing        : "The area is completely open. However, the thick grass is as high as your waist."
	northEastBunker      : "There is a small concrete structure with a thick metal door and no windows. The concrete around the door is scarred by deep gouges."
	northEastView        : "The sheer drop down to the sea is very far. You don't know if you would survive."
	westView             : "The climb down to the beach below might be manageable, but you don't think you would be able to get back up."
	westClearing         : "The area is completely open. However, the thick grass is as high as your waist."
	theCage              : "There is a small compound surrounded by thick, but low, concrete walls that reach your chest. Rows adn rows of razor-sharp barbed wire rise high above your head. On the wouthern wall, there is a loarge hole in the wall and the barbed wire has been shredded."
	eastClearing         : "The area is completely open. However the thick grass is as high as your waist."
	eastView             : "The sheer drop down to the sea looks surviveable, but you wouldn't like to risk it."
	southWestView        : "There is a gentle decline onto a rocky beach. The further south you look, the sandier it appears."
	southWestBunker      : "There is a small concrete structure. It has no doors or windows."
	southClearing        : "The area is completely open. However the thick grass is as high as your waist."
	southEastBunker      : "There is a small concrete structure with a thick metal door and a window. It is hard to tell what the window is made of as it is behind thick metal grating."
	southEastView        : "The sea crashes against the rock below. Although the drop into the water is only a few feet, you don't know if you'd be able to climb out of the water."
	southWestCorner      : "A sandy beach stretches out into the sea. The waves look calm here."
	thePlane             : "This area is filled with the wreckage of a plane. Most of the fusilage is in one piece and one of it's wings is pointing into the air. Most of the plane's surface is charred and fire damaged."
	southernPoint        : "The empty, sandy beach is scarred by the path of a plane that has crashed to the west. The gouge in the sand is pock marked with shrapnel."
	southBeach           : "The area is an empty, sandy beach. There is the occasional piece of driftwood protruding from the sand."
	southEastPoint       : "You feel like you've reached the edge of the island. The sea is more turbulent here."

}